### ISSUE TITLE
PTT not working on Mac starting in v 0.5.0

### ISSUE THREAD

**Issue by jorgeuvo** [pierr3/VectorAudio#30]
I started to use VectorAudio a few weeks ago in the MacOS, in the version 0.4.0. It was all working fine, but this week I updated to version 0.5.0 and since then the PTT functionality stopped working. I am able to test the Mic in the setting panel, I am able to set a PTT key, but when connected to Vatsim, I press the PTT and nothing happen, however I am receiving audio from traffics. Also, when I press the PTT, the TX indicator stays green as nothing being pressed.

Things I have tried:

- changed the input device
- changed the PTT
- reboot my machine
- started the VectorAudio before and after the Euroscope
- Reinstalled the VectorAudio.

I tried it in the stations SBBE_TWR (118.70) and SBEG_TWR (118.30).

Is it really an issue in the v 0.5.0? Or am I missing something? Any help?

**Comment by pierr3** [comment]
Reinstall VectorAudio by deleting the app first (aka move it to the trash can), then install it again. After doing this, go to your settings -> privacy & security -> input monitoring and delete VectorAudio if it's in there. Launch VectorAudio as usual, and macOS should prompt you for permission to give VectorAudio input monitoring access!

There might be an issue at the moment which causes the client to crash on connect, this is due to an API issue and I will be pushing a fix soon.

**Comment by jorgeuvo** [comment]
Thanks for your quick reply @pierr3 . I followed your instructions, tested, and now it is working fine. Lesson learned for the next releases.

By the way, thanks for making Audio alive for  Vatsim controllers on macOS..
