### ISSUE TITLE
ADD STATION added a different station

### ISSUE THREAD

**Issue by bcrockettt** [pierr3/VectorAudio#33]
When I add CYLW_GND, like this, and hit "Add".....

![Vectora_Add_1](https://user-images.githubusercontent.com/125828378/219971863-7f053431-391e-4a36-a029-91f23dc345d0.png)

....it adds CYLW_TWR instead:

![Vectora_Add_2](https://user-images.githubusercontent.com/125828378/219971881-26675872-e57d-4429-8f0b-ca021fafea58.png)

**Comment by pierr3** [comment]
This is normal depending on the configuration your FE has put into AFV. VectorAudio will try to pull the frequency you searched for, as well as all the station defined as VCCS in AFV. It looks like the ground station you tried to add is not defined in database. Would recommend you reach out to your FE.

**Comment by bcrockettt** [comment]
![image](https://user-images.githubusercontent.com/125828378/220512050-3ded7138-6a3d-4672-a258-9057492bf478.png)

**Comment by bcrockettt** [comment]
I can still recreate it by adding the stations _in this order_. Might be a rare thing.

**Comment by pierr3** [comment]
Ah, that explains it. Thanks for sharing!

The architecture of afv-native only allows for one of the same frequency to be used at once. Since you already have another ground station on 121.700, it's ignoring the new one you are trying to add. This could be changed but would require a large overhaul of the underlying library.

If you really need to transmit on 121.700 on that transmitter location, you can just cross-couple your current ground frequency with the tower frequency of that airport and you *should* be able to use 121.7 there too!

**Comment by bcrockettt** [comment]
Ah, I get it. Ok, thanks very much!
