### ISSUE TITLE
Feature Request - G2G Communication

### ISSUE THREAD

**Issue by AUAA320** [pierr3/VectorAudio#64]
Hi there,

Firstly, let me start by expressing my sincerest thanks for this wonderful application. 
Seeing an ATC-Voice-Client for VATSIM being in development is very promising for the future in my opinion!

A feature, which I have been missing for quite some time while controlling on the network is a streamlined, stable and easy-to-use implementation of G2G-Communications, so basically "landline-like "phone calls" between ATCos". In my opinion, the voice Client would be a perfect option for that, and also, I think this feature could really make this amazing client stand out. Current solutions, in my opinion, are rather mediocre: Using Discord, Teamspeak3, and similar solutions is hard across subdivisions, at least here in Europe, VCCS is pretty unstable (crashing itself, crashing EuroScope, not working for certain calls, etc.) in my opinion.

_Please note that I am fully aware that this is a very broad feature request and the implementation probably also is very timing consuming and not as straight-forward as other things._

Thanks for taking this into consideration!
Best regards!

**Comment by pierr3** [comment]
I totally agree about the lack of options on this, and would love to support it. Unfortunately it will not be implemented as a part of this specific project, since this is really supposed to be a simple stopgap measure, and nothing more. Ideally, these features should be embedded in controller clients. Thanks for engaging the discussion !

**Comment by pierr3** [comment]
Closing because of the above!
